name: "Elliot Huang"
synopsis:
  email: "keep.it.sns@gmail.com"
  linkedin: "https://www.linkedin.com/in/elliot-huang-633440233"
description: "Software Engineer with experience in Wi-Fi driver development, OpenWrt, and Android platform integration."
skills:
  - "FWA"
  - "Engineering"
  - "OpenWRT"
  - "Wi-Fi"
  - "Android"
  - "Zig"
  - "Golang"
  - "GCP"
projects:
  - title: "sdat2img"
    description: "A tool to convert Android sparse dat files to raw images."
    url: "https://github.com/binarycraft007/sdat2img"
  - title: "diag-zig"
    description: "Qualcomm (qcom) diag protocol implementation in Zig."
    url: "https://github.com/binarycraft007/diag-zig"
experience:
  - company: "CommScope"
    title: "Software Engineer"
    dates: "May 2022 - May 2025"
    description: "Developed and optimized Wi-Fi driver features for home network cable modems. Worked on OpenSync integration for OpenWrt-based GPON routers. Developed and integrated Vantiva's premium wireless router operating system based on OpenWrt. Led platform integration efforts for Qualcomm SDX platform with OpenWrt/Homeware."
  - company: "MediaTek"
    title: "Wifi driver engineer"
    dates: "December 2021 - February 2022"
    description: "Studied the IEEE 802.11 protocol by analyzing technical specifications and gained insight into MediaTek's Wi-Fi driver architecture."
  - company: "realme"
    title: "Camera Driver Engineer"
    dates: "September 2020 - November 2021"
    description: "Developed and integrated Qualcomm camera software for premium Android smartphones, focusing on bug fixes, third-party algorithm integration, and CTS certification."
education:
  - degree: "Bachelor of Engineering - BE, Electrical and Electronics Engineering"
    institution: "Jiangxi University of Science and Technology"
    dates: "June 2016 - July 2020"
